language: node_js

node_js:
- 'lts/*'

cache: npm

stages:
  - compile
  - test
  - deploy

jobs:
  include:
    - stage: "test"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: npm run unit-test
    
    - stage: "test"
      name: "Integration Tests"
      script: npm run integration-test
    
    # - stage: deploy
    #   name: "Deploy to Blablah"
    #   script: ./tests/integration-tests/integration-tests.js
