language: node_js

node_js:
- node
- 'lts/*'

cache: npm

stages:
  - compile
  - test
  - deploy

jobs:
  include:
    - stage: "test"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: ./tests/unit-tests/unit-tests.js
    
    - stage: "test"
      name: "Integration Tests"
      script: ./tests/integration-tests/integration-tests.js
    
    - stage: deploy
      name: "Deploy to Blablah"
      script: ./tests/integration-tests/integration-tests.js
